"""Generate configs_generated.hpp — one struct per (tile × schedule × scheduler).

Run from the repo root:
    .venv/bin/python docs/research/gemm_sweep/microbench/gen_configs.py
"""
from itertools import product
from pathlib import Path

TILES = [
    # (tile_M, tile_N, tile_K)
    (64, 128, 128), (64, 128, 256), (64, 256, 128), (64, 256, 256),
    (128, 128, 128), (128, 128, 256), (128, 256, 128), (128, 256, 256),
    (256, 128, 128), (256, 128, 256), (256, 256, 128), (256, 256, 256),
]
SCHEDULES = [
    ("Auto",      "cutlass::gemm::collective::KernelScheduleAuto"),
    ("TmaWS",     "cutlass::gemm::KernelTmaWarpSpecialized"),
    ("TmaWSPing", "cutlass::gemm::KernelTmaWarpSpecializedPingpong"),
    ("TmaWSCoop", "cutlass::gemm::KernelTmaWarpSpecializedCooperative"),
]
SCHEDULERS = [
    ("Pers", "void"),
    ("SK",   "cutlass::gemm::StreamKScheduler"),
]


def is_legal(tile, schedule_name, scheduler_name):
    """Pre-filter illegal combinations before template instantiation.

    Returns (legal: bool, reason: str). Reason is empty if legal.

    Empirically-derived constraints from iter-1 build log on SM120 blockscaled:
    - KernelScheduleAuto on SM120 NVFP4 resolves to
      KernelTmaWarpSpecializedCooperativeBlockScaledSm120, which requires
      tile_M >= 128 (Cooperative kernel static_assert).
    - KernelTmaWarpSpecializedCooperative also requires tile_M >= 128.
    - KernelTmaWarpSpecialized (plain, non-Coop/non-Ping) fails the SM120
      blockscaled CollectiveBuilder ("Could not build a collective for given
      parameters") — no mainloop specialization exists, skip all tiles.
    - StreamKScheduler only pairs with TmaWSCoop.
    Pingpong is allowed through; CUTLASS will reject at instantiation any
    Pingpong tile that fails NumMMAThreads==128 etc.
    """
    tm, tn, tk = tile

    # StreamKScheduler only pairs with TmaWSCoop (cooperative).
    if scheduler_name == "SK" and schedule_name != "TmaWSCoop":
        return False, f"StreamK requires TmaWSCoop, got {schedule_name}"

    # Plain TmaWS has no SM120 blockscaled mainloop — builder fails.
    if schedule_name == "TmaWS":
        return False, "plain TmaWS has no SM120 blockscaled CollectiveBuilder"

    # Auto and Cooperative both resolve to Cooperative path → tile_M >= 128.
    if schedule_name in ("Auto", "TmaWSCoop") and tm < 128:
        return False, f"{schedule_name} requires tile_M >= 128, got {tm}"

    # Pingpong on SM120 blockscaled fails at load_init for tile_M=64; the
    # blockscaled Pingpong mainloop needs tile_M >= 128 as well. Skip.
    if schedule_name == "TmaWSPing" and tm < 128:
        return False, f"TmaWSPing requires tile_M >= 128, got {tm}"

    # tile_K=256 combined with large tile_M*tile_N (>= 32768) forces the
    # StageCountAutoCarveout to Stages=1, which CollectiveMma rejects
    # ("Specialization requires Stages set to value 2 or more"). Affects
    # all SM120 blockscaled schedules (Auto/Pingpong/Cooperative). Skip.
    if tk == 256 and tm * tn >= 32768:
        return False, f"{schedule_name} SMEM insufficient for {tm}x{tn}x{tk} (Stages<2)"

    return True, ""


def main():
    structs = []
    names = []
    skipped = []
    for (tm, tn, tk), (sn, sty), (rn, rty) in product(TILES, SCHEDULES, SCHEDULERS):
        name = f"Cfg_{tm}x{tn}x{tk}_{sn}_{rn}"
        legal, reason = is_legal((tm, tn, tk), sn, rn)
        if not legal:
            skipped.append((name, reason))
            continue
        names.append(name)
        structs.append(f"""
struct {name} {{
    using MmaTileShape = cute::Shape<cute::_{tm}, cute::_{tn}, cute::_{tk}>;
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using PerSmTileShape_MNK = cute::Shape<cute::_{tm}, cute::_{tn}, cute::_{tk}>;
    using KernelSchedule = {sty};
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = {rty};
    static constexpr const char* name = "{name}";
}};""")

    out = Path(__file__).parent / "configs_generated.hpp"
    header = (
        "#pragma once\n"
        "// Auto-generated by gen_configs.py — do not edit by hand.\n"
        "// Covers 12 tiles x 4 schedules x 2 schedulers = 96 configs.\n"
        "// Pre-skipped illegal combinations (StreamK requires cooperative schedule).\n"
        "// Remaining illegal combinations are pruned by CUTLASS at template-instantiation\n"
        "// or rejected at runtime via can_implement()/initialize() (both return\n"
        "// -1.0 from the microbench and are excluded from downstream analysis).\n\n"
    )
    out.write_text(header + "\n".join(structs) + "\n")
    print(f"Generated {len(names)} configs -> {out}")
    print(f"Pre-skipped {len(skipped)} illegal combinations:")
    for n, reason in skipped:
        print(f"  SKIP {n}: {reason}")
    # Also print the name list so gen_dispatcher.py doesn't need to re-parse
    for n in names:
        print(f"  {n}")


if __name__ == "__main__":
    main()
