"""Generate csrc/libtorch_stable/quantization/fp4/nvfp4_shortlist_configs.hpp
from shortlist.json.

Emits:
  - struct ShortlistCfg_<idx> for each unique config in shortlist.json
  - try_run_shortlist_config<OutType>(idx, ...) template function that
    dispatches to the correct Gemm instantiation

Run from the repo root:
    .venv/bin/python docs/research/gemm_sweep/gen_shortlist_header.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

CFG_RE = re.compile(
    r"Cfg_(?P<tm>\d+)x(?P<tn>\d+)x(?P<tk>\d+)_(?P<sched>Auto|TmaWS|TmaWSPing|TmaWSCoop)_(?P<tsched>Pers|SK)"
)
SCHED_MAP = {
    "Auto":      "cutlass::gemm::collective::KernelScheduleAuto",
    "TmaWS":     "cutlass::gemm::KernelTmaWarpSpecialized",
    "TmaWSPing": "cutlass::gemm::KernelTmaWarpSpecializedPingpong",
    "TmaWSCoop": "cutlass::gemm::KernelTmaWarpSpecializedCooperative",
}
TSCHED_MAP = {
    "Pers": "void",
    "SK":   "cutlass::gemm::StreamKScheduler",
}

# smoke_M256 is an alias for the production sm120_fp4_config_M256 path:
# tile 128x128x128, KernelScheduleAuto, persistent scheduler.
ALIAS_MAP = {
    "smoke_M256": ("128", "128", "128", "Auto", "Pers"),
}


def parse_name(name: str):
    if name in ALIAS_MAP:
        return ALIAS_MAP[name]
    m = CFG_RE.match(name)
    if not m:
        raise ValueError(f"Bad config name: {name}")
    return (m.group("tm"), m.group("tn"), m.group("tk"),
            m.group("sched"), m.group("tsched"))


def emit(shortlist_path: Path, out_path: Path):
    data = json.loads(shortlist_path.read_text())
    configs = data["all_configs"]

    structs = []
    cases = []
    for idx, name in enumerate(configs):
        tm, tn, tk, sched_key, tsched_key = parse_name(name)
        sched = SCHED_MAP[sched_key]
        tsched = TSCHED_MAP[tsched_key]
        sname = f"ShortlistCfg_{idx}"
        structs.append(f"""
// [{idx}] {name}
struct {sname} {{
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_{tm}, cute::_{tn}, cute::_{tk}>;
    using PerSmTileShape_MNK = cute::Shape<cute::_{tm}, cute::_{tn}, cute::_{tk}>;
    using KernelSchedule = {sched};
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = {tsched};
    static constexpr const char* name = "{name}";
}};""")
        cases.append(
            f'    case {idx}: runGemm<typename Fp4GemmSm120Tuneable<{sname}, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;'
        )

    body = "\n".join(structs) + "\n"
    body += """
template <typename OutType>
inline bool try_run_shortlist_config(int idx,
                                     torch::stable::Tensor& D,
                                     torch::stable::Tensor const& A,
                                     torch::stable::Tensor const& B,
                                     torch::stable::Tensor const& A_sf,
                                     torch::stable::Tensor const& B_sf,
                                     torch::stable::Tensor const& alpha,
                                     int m, int n, int k, cudaStream_t stream) {
    switch (idx) {
""" + "\n".join(cases) + """
        default: return false;
    }
}
"""
    out_path.write_text(
        "#pragma once\n"
        "// Auto-generated by docs/research/gemm_sweep/gen_shortlist_header.py\n"
        "// Source: benchmarks/nvllm/traces/gemm_sweep_sm120/2026-04-21-qwen35-27b/shortlist.json\n"
        "// Do not edit by hand — regenerate after shortlist.json changes.\n\n"
        + body
    )
    print(f"Emitted {len(configs)} shortlist configs -> {out_path}")
    for idx, name in enumerate(configs):
        print(f"  [{idx}] {name}")


if __name__ == "__main__":
    emit(
        Path("benchmarks/nvllm/traces/gemm_sweep_sm120/2026-04-21-qwen35-27b/shortlist.json"),
        Path("csrc/libtorch_stable/quantization/fp4/nvfp4_shortlist_configs.hpp"),
    )
