#pragma once
// Auto-generated by docs/research/gemm_sweep/gen_shortlist_header.py
// Source: benchmarks/nvllm/traces/gemm_sweep_sm120/2026-04-21-qwen35-27b/shortlist.json
// Do not edit by hand — regenerate after shortlist.json changes.


// [0] Cfg_128x128x128_TmaWSCoop_Pers
struct ShortlistCfg_0 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_128, cute::_128, cute::_128>;
    using PerSmTileShape_MNK = cute::Shape<cute::_128, cute::_128, cute::_128>;
    using KernelSchedule = cutlass::gemm::KernelTmaWarpSpecializedCooperative;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = void;
    static constexpr const char* name = "Cfg_128x128x128_TmaWSCoop_Pers";
};

// [1] Cfg_128x128x128_TmaWSPing_Pers
struct ShortlistCfg_1 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_128, cute::_128, cute::_128>;
    using PerSmTileShape_MNK = cute::Shape<cute::_128, cute::_128, cute::_128>;
    using KernelSchedule = cutlass::gemm::KernelTmaWarpSpecializedPingpong;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = void;
    static constexpr const char* name = "Cfg_128x128x128_TmaWSPing_Pers";
};

// [2] Cfg_128x128x256_Auto_Pers
struct ShortlistCfg_2 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_128, cute::_128, cute::_256>;
    using PerSmTileShape_MNK = cute::Shape<cute::_128, cute::_128, cute::_256>;
    using KernelSchedule = cutlass::gemm::collective::KernelScheduleAuto;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = void;
    static constexpr const char* name = "Cfg_128x128x256_Auto_Pers";
};

// [3] Cfg_128x128x256_TmaWSCoop_Pers
struct ShortlistCfg_3 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_128, cute::_128, cute::_256>;
    using PerSmTileShape_MNK = cute::Shape<cute::_128, cute::_128, cute::_256>;
    using KernelSchedule = cutlass::gemm::KernelTmaWarpSpecializedCooperative;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = void;
    static constexpr const char* name = "Cfg_128x128x256_TmaWSCoop_Pers";
};

// [4] Cfg_128x128x256_TmaWSCoop_SK
struct ShortlistCfg_4 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_128, cute::_128, cute::_256>;
    using PerSmTileShape_MNK = cute::Shape<cute::_128, cute::_128, cute::_256>;
    using KernelSchedule = cutlass::gemm::KernelTmaWarpSpecializedCooperative;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = cutlass::gemm::StreamKScheduler;
    static constexpr const char* name = "Cfg_128x128x256_TmaWSCoop_SK";
};

// [5] Cfg_128x128x256_TmaWSPing_Pers
struct ShortlistCfg_5 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_128, cute::_128, cute::_256>;
    using PerSmTileShape_MNK = cute::Shape<cute::_128, cute::_128, cute::_256>;
    using KernelSchedule = cutlass::gemm::KernelTmaWarpSpecializedPingpong;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = void;
    static constexpr const char* name = "Cfg_128x128x256_TmaWSPing_Pers";
};

// [6] Cfg_128x256x128_Auto_Pers
struct ShortlistCfg_6 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_128, cute::_256, cute::_128>;
    using PerSmTileShape_MNK = cute::Shape<cute::_128, cute::_256, cute::_128>;
    using KernelSchedule = cutlass::gemm::collective::KernelScheduleAuto;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = void;
    static constexpr const char* name = "Cfg_128x256x128_Auto_Pers";
};

// [7] Cfg_128x256x128_TmaWSCoop_Pers
struct ShortlistCfg_7 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_128, cute::_256, cute::_128>;
    using PerSmTileShape_MNK = cute::Shape<cute::_128, cute::_256, cute::_128>;
    using KernelSchedule = cutlass::gemm::KernelTmaWarpSpecializedCooperative;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = void;
    static constexpr const char* name = "Cfg_128x256x128_TmaWSCoop_Pers";
};

// [8] Cfg_128x256x128_TmaWSCoop_SK
struct ShortlistCfg_8 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_128, cute::_256, cute::_128>;
    using PerSmTileShape_MNK = cute::Shape<cute::_128, cute::_256, cute::_128>;
    using KernelSchedule = cutlass::gemm::KernelTmaWarpSpecializedCooperative;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = cutlass::gemm::StreamKScheduler;
    static constexpr const char* name = "Cfg_128x256x128_TmaWSCoop_SK";
};

// [9] Cfg_256x128x128_Auto_Pers
struct ShortlistCfg_9 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_256, cute::_128, cute::_128>;
    using PerSmTileShape_MNK = cute::Shape<cute::_256, cute::_128, cute::_128>;
    using KernelSchedule = cutlass::gemm::collective::KernelScheduleAuto;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = void;
    static constexpr const char* name = "Cfg_256x128x128_Auto_Pers";
};

// [10] Cfg_256x128x128_TmaWSCoop_Pers
struct ShortlistCfg_10 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_256, cute::_128, cute::_128>;
    using PerSmTileShape_MNK = cute::Shape<cute::_256, cute::_128, cute::_128>;
    using KernelSchedule = cutlass::gemm::KernelTmaWarpSpecializedCooperative;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = void;
    static constexpr const char* name = "Cfg_256x128x128_TmaWSCoop_Pers";
};

// [11] smoke_M256
struct ShortlistCfg_11 {
    using ClusterShape = cute::Shape<cute::_1, cute::_1, cute::_1>;
    using MmaTileShape = cute::Shape<cute::_128, cute::_128, cute::_128>;
    using PerSmTileShape_MNK = cute::Shape<cute::_128, cute::_128, cute::_128>;
    using KernelSchedule = cutlass::gemm::collective::KernelScheduleAuto;
    using EpilogueSchedule = cutlass::epilogue::collective::EpilogueScheduleAuto;
    using TileScheduler = void;
    static constexpr const char* name = "smoke_M256";
};

template <typename OutType>
inline bool try_run_shortlist_config(int idx,
                                     torch::stable::Tensor& D,
                                     torch::stable::Tensor const& A,
                                     torch::stable::Tensor const& B,
                                     torch::stable::Tensor const& A_sf,
                                     torch::stable::Tensor const& B_sf,
                                     torch::stable::Tensor const& alpha,
                                     int m, int n, int k, cudaStream_t stream) {
    switch (idx) {
    case 0: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_0, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
    case 1: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_1, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
    case 2: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_2, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
    case 3: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_3, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
    case 4: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_4, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
    case 5: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_5, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
    case 6: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_6, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
    case 7: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_7, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
    case 8: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_8, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
    case 9: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_9, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
    case 10: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_10, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
    case 11: runGemm<typename Fp4GemmSm120Tuneable<ShortlistCfg_11, OutType>::Gemm>(D, A, B, A_sf, B_sf, alpha, m, n, k, stream); return true;
        default: return false;
    }
}
