#pragma once
// Auto-generated by docs/research/gemm_sweep/gen_winners_header.py
// Source: benchmarks/nvllm/traces/gemm_sweep_sm120/2026-04-21-qwen35-27b/winners.json
// Do not edit by hand — regenerate after winners.json changes.

#include <cstdio>
#include <cstdlib>

namespace nvllm::fp4 {

struct ShapeWinners {
    int N;
    int K;
    int idx_16_32;
    int idx_64_128;
    int idx_192_256;
    const char* shape_name;  // debug only — NVLLM_FP4_GEMM_LOG_TABLE=1
};

inline constexpr ShapeWinners kWinnersTable[] = {
    {   8192,   5120, /*16-32*/  6, /*64-128*/ 11, /*192-256*/  1, "qwen35_27b/qkv_proj" },
    {   5120,   6144, /*16-32*/  6, /*64-128*/  5, /*192-256*/ 10, "qwen35_27b/o_proj" },
    {  34816,   5120, /*16-32*/  2, /*64-128*/  3, /*192-256*/  2, "qwen35_27b/gate_up_proj" },
    {   5120,  17408, /*16-32*/  2, /*64-128*/  2, /*192-256*/  2, "qwen35_27b/down_proj" },
};

// Returns ShortlistCfg idx or -1 if (n,k) not in table / mp2 not in mid band.
inline int lookup_m_mid_winner(int n, int k, int mp2) {
    for (auto const& w : kWinnersTable) {
        if (w.N != n || w.K != k) continue;
        int idx;
        switch (mp2) {
            case 32:            idx = w.idx_16_32;  break;
            case 64: case 128:  idx = w.idx_64_128; break;
            case 256:           idx = w.idx_192_256; break;
            default:            return -1;
        }
        if (const char* dbg = std::getenv("NVLLM_FP4_GEMM_LOG_TABLE"); dbg && dbg[0] == '1') {
            std::fprintf(stderr, "[nvllm] fp4 table: %s mp2=%d -> idx=%d\n",
                         w.shape_name, mp2, idx);
        }
        return idx;
    }
    return -1;
}

} // namespace nvllm::fp4
